### PR TITLE
Particle System: Implement smooth capacity reduction

### PR DESCRIPTION
**Pull request by Adolio**
Hey @PrimaryFeather,

Here is a small PR to smooth the capacity reduction. 

### Changes

- Capacity reduction no longer instantly and randomly eliminates existing particles, but lets them live to the end of their lifetime. This results with smoother capacity transitions when for instance particles are covering the whole camera space and a zoom in is occurring.

Best,
Aurélien

### CODE REVIEW

**Comment by Adolio** [comment]
☝ Please don't merge, I just noticed an issue 😅

**Comment by PrimaryFeather** [comment]
Thanks, Aurélien! I wasn't aware of this issue - thanks for looking into it! I'll wait for the merge until I've got your "go". 😁

**Comment by Adolio** [comment]
It should be all good now, thanks in advance for your review 🙂

**Comment by PrimaryFeather** [comment]
That looks useful! Thanks for taking the time to making this change! 🙏

**Comment by Adolio** [comment]
Thanks a lot for your review & approval Daniel!

**Pull request merged**
